[
"AdverseEvent",
"AllergyIntolerance",
"AssessmentOrder",
"AssessmentPerformed",
"AssessmentRecommended",
"CareGoal",
"CommunicationPerformed",
"DeviceApplied",
"DeviceOrder",
"DeviceRecommended",
"Diagnosis",
"DiagnosticStudyOrder",
"DiagnosticStudyPerformed",
"DiagnosticStudyRecommended",
"EncounterOrder",
"EncounterPerformed",
"EncounterRecommended",
"FamilyHistory",
"ImmunizationAdministered",
"ImmunizationOrder",
"InterventionOrder",
"InterventionPerformed",
"InterventionRecommended",
"LaboratoryTestOrder",
"LaboratoryTestPerformed",
"LaboratoryTestRecommended",
"MedicationActive",
"MedicationAdministered",
"MedicationDischarge",
"MedicationDispensed",
"MedicationOrder",
"Participation",
"PatientCareExperience",
"PatientCharacteristic",
"PatientCharacteristicBirthdate",
"PatientCharacteristicClinicalTrialParticipant",
"PatientCharacteristicEthnicity",
"PatientCharacteristicExpired",
"PatientCharacteristicPayer",
"PatientCharacteristicRace",
"PatientCharacteristicSex",
"PhysicalExamOrder",
"PhysicalExamPerformed",
"PhysicalExamRecommended",
"ProcedureOrder",
"ProcedurePerformed",
"ProcedureRecommended",
"ProviderCareExperience",
"RelatedPerson",
"SubstanceAdministered",
"SubstanceOrder",
"SubstanceRecommended",
"Symptom"
]
